services:
  postgresql:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_HOST_AUTH_METHOD=trust