name: 'Maven Build'
description: 'Maven targeting java or native build'
inputs:
  native:  # id of input
    description: 'Target native build'
    default: 'false'

runs:
  using: 'composite'

  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - id: maven-options
      uses: ./.github/actions/maven-options
      with:
        native: ${{ inputs.native }}
    - name: Build with Maven
      shell: bash
      env:
        MVN_OPTIONS: ${{ steps.maven-options.outputs.mvn-options }}
      run: mvn $MVN_OPTIONS
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.maven-options.outputs.artifacts-name }}
        path: ${{ steps.maven-options.outputs.targets }}