name: 'Maven Build'
description: 'Maven targeting java or native build'
inputs:
  native:  # id of input
    description: 'Target native build'
    default: 'false'

runs:
  using: 'composite'

  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Compute Maven options
      run: |
        echo "hello"
