name: Native image build

on:
  push:
    branches:
      - main
      - develop

  workflow_call:

jobs:
  maven-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests=true -Dnative -Dquarkus.native.sources-only=true -Dstyle.color=always -Djansi.force=true --no-transfer-progress

      - uses: actions/upload-artifact@v4
        with:
          name: native-jars
          path: registry/target/**/*.jar

  image-build:

    runs-on: ubuntu-latest
    needs:
      - maven-build

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pom.xml
            registry/pom.xml
            registry/src/main/docker/Dockerfile.native
            registry/src/main/docker/Dockerfile.native-micro
          sparse-checkout-cone-mode: false
      - uses: actions/download-artifact@v4
        with:
          name: native-jars
          path: registry/target/quarkus-app
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: sudo apt-get -y install podman
      - name: Build image with podman
        run: |
          echo "${{vars.DOCKERHUB_USERNAME}}"
          mvn install \
            -DskipTests=true \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.username=${{vars.DOCKERHUB_USERNAME}} \
            -Dquarkus.container-image.password=${{secrets.DOCKERHUB_PASSWORD}} \
            -Dquarkus.container-image.group=wvandenberghe \
            -Dquarkus.container-image.name=dockerregistry \
            -Dquarkus.container-image.tag=native-1.0.0-SNAPSHOT \
            -Dnative \
            -Dstyle.color=always \
            -Djansi.force=true \
            --no-transfer-progress

  image-scan:

    runs-on: ubuntu-latest
    needs:
      - image-build

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/wvandenberghe/dockerregistry:native-1.0.0-SNAPSHOT'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'